import type { Game, Observation } from './types'

/**
 * The sbaby game library.
 *
 * Each game is a short play session for one parent and one baby. The "watchFor" list is what
 * the parent ticks while playing; items linked to a milestone feed growth tracking.
 *
 * NOT MEDICALLY REVIEWED. These games follow common guidance (CDC, AAP, WHO) but must be reviewed
 * by a pediatrician or early-childhood specialist before sbaby is offered to other families.
 */
const o = (id: string, text: string, milestoneId?: string): Observation => ({ id, text, milestoneId })

const TUMMY_SAFETY = 'Tummy time only while baby is awake and you are watching. Stop if baby is very upset.'
const CHOKING_SAFETY = 'Use only objects too big to fit through a toilet-paper tube. Never leave small items within reach.'

export const games: Game[] = [
  // ───────────────────────── 0–3 months ─────────────────────────
  {
    id: 'face-to-face-chat',
    title: 'Face-to-face chat',
    ageMinDays: 0,
    ageMaxDays: 120,
    areas: ['social', 'language'],
    durationMin: 5,
    materials: [],
    steps: [
      'Hold baby about 20–30 cm from your face. That is where newborns see best.',
      'Talk slowly in a sing-song voice. Say their name, describe your day.',
      'Pause after each sentence, as if waiting for a reply. Smile when baby looks at you.',
    ],
    whyItHelps: 'Faces are the most interesting thing in a young baby’s world. Back-and-forth “talk” is the start of conversation.',
    safetyNotes: [],
    watchFor: [
      o('looks-face', 'Looks at your face', 'm2-looks-face'),
      o('smiles-back', 'Smiles back when you smile or talk', 'm2-smiles-back'),
      o('sounds', 'Makes a sound that isn’t crying', 'm2-sounds'),
      o('sounds-back', 'Makes sounds back when you pause', 'm4-sounds-back'),
    ],
  },
  {
    id: 'tummy-on-chest',
    title: 'Tummy time on your chest',
    ageMinDays: 0,
    ageMaxDays: 90,
    areas: ['motor', 'social'],
    durationMin: 5,
    materials: [],
    steps: [
      'Recline on a sofa or bed, propped up at a comfortable angle.',
      'Lay baby tummy-down on your chest, facing you.',
      'Talk and make faces so baby wants to lift their head to see you.',
    ],
    whyItHelps: 'Lifting the head against gravity builds the neck and back strength needed for rolling, sitting and crawling.',
    safetyNotes: [TUMMY_SAFETY, 'Keep one hand on baby’s back. Do this only while you are fully awake.'],
    watchFor: [
      o('head-up', 'Lifts head up, even briefly', 'm2-head-up-tummy'),
      o('limbs', 'Moves both arms and both legs', 'm2-moves-limbs'),
      o('looks', 'Looks up at your face', 'm2-looks-face'),
    ],
  },
  {
    id: 'high-contrast-cards',
    title: 'High-contrast cards',
    ageMinDays: 0,
    ageMaxDays: 120,
    areas: ['cognitive'],
    durationMin: 4,
    materials: ['Black-and-white picture cards (or draw bold stripes and circles on paper)'],
    steps: [
      'Hold a card 20–30 cm from baby’s face while they lie on their back.',
      'Wait until baby focuses on it, then move it slowly left and right.',
      'Swap cards when baby looks away. Two or three cards is plenty.',
    ],
    whyItHelps: 'Strong contrast is what young eyes see best. Following it trains focus and eye tracking.',
    safetyNotes: [],
    watchFor: [
      o('fixes', 'Looks at the card for several seconds', 'm2-looks-toy'),
      o('tracks', 'Follows the card as it moves', 'm2-watches-move'),
    ],
  },
  {
    id: 'follow-my-face',
    title: 'Follow my face',
    ageMinDays: 0,
    ageMaxDays: 120,
    areas: ['cognitive', 'social'],
    durationMin: 4,
    materials: [],
    steps: [
      'Lay baby on their back and lean over so they can see your face.',
      'Once they look at you, slowly move your head to one side, then the other.',
      'Then move out of sight to one side and call their name softly.',
    ],
    whyItHelps: 'Tracking a moving face builds visual attention; finding your voice builds listening skills.',
    safetyNotes: [],
    watchFor: [
      o('tracks', 'Watches you as you move', 'm2-watches-move'),
      o('voice', 'Turns head towards your voice', 'm4-turns-voice'),
    ],
  },
  {
    id: 'leg-bicycles',
    title: 'Leg bicycles & baby massage',
    ageMinDays: 0,
    ageMaxDays: 150,
    areas: ['motor', 'social'],
    durationMin: 6,
    materials: ['A little baby-safe oil (optional)'],
    steps: [
      'Lay baby on their back on a soft, warm surface.',
      'Gently stroke arms, legs and tummy with slow, firm strokes, naming each body part.',
      'Hold both feet and slowly “cycle” the legs, then stroke each palm.',
    ],
    whyItHelps: 'Touch calms the nervous system and builds bonding; moving limbs builds body awareness.',
    safetyNotes: ['Skip if baby is unwell, has a rash, or has just eaten.'],
    watchFor: [
      o('calms', 'Calms down with your touch and voice', 'm2-calms'),
      o('limbs', 'Kicks and moves both arms and legs', 'm2-moves-limbs'),
      o('hands', 'Opens hands (not always in a fist)', 'm2-opens-hands'),
    ],
  },
  {
    id: 'sound-surprise',
    title: 'Sound surprise',
    ageMinDays: 0,
    ageMaxDays: 150,
    areas: ['language', 'cognitive'],
    durationMin: 3,
    materials: ['A rattle, bell, or two spoons'],
    steps: [
      'While baby lies calmly, stand about a metre away and out of sight.',
      'Make one clear sound: shake the rattle, ring the bell, or clink the spoons.',
      'Wait and watch. Then try from the other side.',
    ],
    whyItHelps: 'Reacting to sound is an early check of hearing and attention.',
    safetyNotes: ['Never make loud sounds close to baby’s ears.'],
    watchFor: [
      o('reacts', 'Reacts to the sound (startles, blinks, goes still)', 'm2-loud-sounds'),
      o('turns', 'Turns head towards the sound or your voice', 'm4-turns-voice'),
    ],
  },
  {
    id: 'peek-in-hello',
    title: 'Peek-in hello',
    ageMinDays: 0,
    ageMaxDays: 150,
    areas: ['social'],
    durationMin: 3,
    materials: [],
    steps: [
      'Step out of baby’s view for a moment.',
      'Walk back in with a big smile and a cheerful “Hello, [name]!”.',
      'Stay close and chat for a minute, then repeat.',
    ],
    whyItHelps: 'Baby learns that people come back and that they can get your attention, the base of secure attachment.',
    safetyNotes: [],
    watchFor: [
      o('happy', 'Seems happy to see you when you walk up', 'm2-happy-see'),
      o('smiles-first', 'Smiles on their own to get your attention', 'm4-smiles-attention'),
      o('keeps', 'Moves or makes sounds to keep your attention', 'm4-keeps-attention'),
    ],
  },
  {
    id: 'hand-discovery',
    title: 'Hand discovery',
    ageMinDays: 45,
    ageMaxDays: 150,
    areas: ['motor', 'cognitive'],
    durationMin: 4,
    materials: [],
    steps: [
      'Hold baby’s hands up in front of their face.',
      'Gently clap them together, wiggle the fingers and sing a short rhyme.',
      'Let go and see what baby does with their own hands.',
    ],
    whyItHelps: 'Discovering their own hands is the start of reaching, grasping and hand-eye coordination.',
    safetyNotes: [],
    watchFor: [
      o('looks-hands', 'Looks at their hands with interest', 'm4-looks-hands'),
      o('mouth', 'Brings hands to mouth', 'm4-hands-mouth'),
      o('opens', 'Opens hands and spreads fingers', 'm2-opens-hands'),
    ],
  },
  {
    id: 'coo-conversation',
    title: 'Coo conversation',
    ageMinDays: 45,
    ageMaxDays: 200,
    areas: ['language', 'social'],
    durationMin: 5,
    materials: [],
    steps: [
      'Wait until baby makes a sound on their own.',
      'Copy it back exactly (“oooh!”), then pause and wait.',
      'Keep the “conversation” going for as many turns as baby wants.',
    ],
    whyItHelps: 'Copying baby’s sounds teaches turn-taking, the rhythm of every real conversation.',
    safetyNotes: [],
    watchFor: [
      o('coos', 'Coos (“oooo”, “aahh”)', 'm4-coos'),
      o('back', 'Makes sounds back when you copy them', 'm4-sounds-back'),
      o('turns', 'Takes turns making sounds with you', 'm6-turn-taking'),
    ],
  },
  {
    id: 'upright-look-around',
    title: 'Upright look-around',
    ageMinDays: 45,
    ageMaxDays: 150,
    areas: ['motor', 'cognitive'],
    durationMin: 4,
    materials: [],
    steps: [
      'Hold baby upright against your chest, facing outwards, one arm under their bottom.',
      'Walk slowly around the room and name what you see: “Lamp! Window! Plant!”.',
      'Stop at interesting things and let baby look.',
    ],
    whyItHelps: 'Being upright strengthens neck control, and a new view of the room feeds curiosity.',
    safetyNotes: ['Support baby’s head if it still wobbles.'],
    watchFor: [
      o('head', 'Holds head steady without your support', 'm4-head-steady'),
      o('watches', 'Follows moving things with their eyes', 'm2-watches-move'),
    ],
  },
  {
    id: 'swat-the-toy',
    title: 'Swat the toy',
    ageMinDays: 60,
    ageMaxDays: 180,
    areas: ['motor', 'cognitive'],
    durationMin: 5,
    materials: ['A soft toy or rattle on a ribbon, or a play gym'],
    steps: [
      'Lay baby on their back.',
      'Dangle the toy within arm’s reach above their chest.',
      'Jiggle it to get attention, then hold it still and let baby try to hit or grab it.',
      'Once they touch it, put it into their hand.',
    ],
    whyItHelps: 'Swatting turns into reaching and grasping: the first steps of hand-eye coordination.',
    safetyNotes: ['Never leave ribbons or strings near baby when you are not holding them.'],
    watchFor: [
      o('swings', 'Swings an arm at the toy', 'm4-swings-arm'),
      o('holds', 'Holds the toy when you put it in their hand', 'm4-holds-toy'),
      o('reaches', 'Reaches out to grab the toy', 'm6-reaches-grab'),
    ],
  },
  {
    id: 'gentle-giggles',
    title: 'Gentle giggles',
    ageMinDays: 75,
    ageMaxDays: 240,
    areas: ['social', 'language'],
    durationMin: 4,
    materials: [],
    steps: [
      'Try “I’m gonna get your tummy!” with a slow build-up, then a gentle tickle.',
      'Try blowing softly on baby’s tummy or making a silly sound.',
      'Repeat whatever gets a reaction. Stop before baby gets overexcited.',
    ],
    whyItHelps: 'Laughing together is pure bonding, and anticipation (“here it comes!”) is an early thinking skill.',
    safetyNotes: ['Keep tickles gentle and short. Stop if baby turns away or fusses.'],
    watchFor: [
      o('chuckles', 'Chuckles', 'm4-chuckles'),
      o('laughs', 'Laughs out loud', 'm6-laughs'),
      o('squeals', 'Squeals with excitement', 'm6-squeals'),
    ],
  },
  {
    id: 'tummy-mirror',
    title: 'Tummy time with a mirror',
    ageMinDays: 60,
    ageMaxDays: 200,
    areas: ['motor', 'social'],
    durationMin: 5,
    materials: ['An unbreakable baby mirror'],
    steps: [
      'Lay baby on their tummy on a play mat.',
      'Stand the mirror just in front of them so they can see their face.',
      'Lie down next to baby so they see you in the mirror too.',
    ],
    whyItHelps: 'The mirror makes tummy time interesting enough to keep pushing up, which builds arm and core strength.',
    safetyNotes: [TUMMY_SAFETY, 'Use only a shatter-proof baby mirror.'],
    watchFor: [
      o('elbows', 'Pushes up onto elbows or forearms', 'm4-pushes-elbows'),
      o('straight', 'Pushes up with straight arms', 'm6-straight-arms'),
      o('mirror', 'Looks at their reflection with interest', 'm6-mirror'),
    ],
  },
  {
    id: 'mealtime-chatter',
    title: 'Mealtime chatter',
    ageMinDays: 90,
    ageMaxDays: 300,
    areas: ['social', 'cognitive'],
    durationMin: 10,
    materials: ['Baby’s usual milk or food'],
    steps: [
      'Before feeding, show baby the breast, bottle or spoon and say “Milk time!” or “Yum!”.',
      'During the feed, talk softly and pause for baby’s sounds.',
      'Let baby lead: watch for signs they want more or are done.',
    ],
    whyItHelps: 'Feeding is a social moment. Reading baby’s cues teaches them their signals work.',
    safetyNotes: ['Never force food. Stop when baby shows they are done.'],
    watchFor: [
      o('opens', 'Opens mouth when they see breast, bottle or spoon', 'm4-opens-mouth'),
      o('closes', 'Closes lips to show they don’t want more', 'm6-closes-lips'),
      o('turns', 'Takes turns making sounds with you', 'm6-turn-taking'),
    ],
  },

  // ───────────────────────── 4–6 months ─────────────────────────
  {
    id: 'roll-to-the-toy',
    title: 'Roll to the toy',
    ageMinDays: 100,
    ageMaxDays: 240,
    areas: ['motor'],
    durationMin: 5,
    materials: ['A favourite toy'],
    steps: [
      'Place baby on their tummy on the floor.',
      'Show the toy, then move it slowly up and to one side, so baby turns to follow it.',
      'If baby gets halfway, gently help them finish the roll by guiding their hip.',
    ],
    whyItHelps: 'Rolling is baby’s first way of getting around on their own, and it strengthens the whole body.',
    safetyNotes: [TUMMY_SAFETY, 'Play on the floor. Babies can roll off beds and sofas surprisingly early.'],
    watchFor: [
      o('rolls', 'Rolls from tummy to back', 'm6-rolls-tummy-back'),
      o('reaches', 'Reaches to grab the toy', 'm6-reaches-grab'),
    ],
  },
  {
    id: 'raspberry-duet',
    title: 'Raspberry duet',
    ageMinDays: 100,
    ageMaxDays: 270,
    areas: ['language', 'social'],
    durationMin: 4,
    materials: [],
    steps: [
      'Face baby and blow a raspberry (tongue out, blow).',
      'Pause, wait. If baby makes any sound, copy it back.',
      'Mix in squeals, “ba-ba” and lip pops, one at a time.',
    ],
    whyItHelps: 'Playing with lips and tongue is practice for speech sounds.',
    safetyNotes: [],
    watchFor: [
      o('raspberries', 'Blows raspberries', 'm6-raspberries'),
      o('squeals', 'Makes squealing noises', 'm6-squeals'),
      o('turns', 'Takes turns making sounds with you', 'm6-turn-taking'),
    ],
  },
  {
    id: 'texture-treasure',
    title: 'Texture treasure',
    ageMinDays: 120,
    ageMaxDays: 300,
    areas: ['cognitive', 'motor'],
    durationMin: 6,
    materials: ['3–4 safe objects with different textures: a soft cloth, a silicone spatula, a wooden spoon, a crinkly toy'],
    steps: [
      'Sit baby supported, or lay them on their tummy.',
      'Offer one object at a time and name it: “Soft! Bumpy!”.',
      'Let baby explore freely, including mouthing. That is how babies learn.',
    ],
    whyItHelps: 'Hands and mouth are baby’s main tools for learning what things are.',
    safetyNotes: [CHOKING_SAFETY],
    watchFor: [
      o('reaches', 'Reaches for the object they want', 'm6-reaches-grab'),
      o('mouths', 'Puts the object in their mouth to explore it', 'm6-mouths'),
      o('passes', 'Passes it from one hand to the other', 'm9-hand-to-hand'),
    ],
  },
  {
    id: 'family-hello-round',
    title: 'Family hello round',
    ageMinDays: 150,
    ageMaxDays: 330,
    areas: ['social'],
    durationMin: 5,
    materials: ['Family members or visitors'],
    steps: [
      'When family or a visitor is around, hold baby and let each person say hello in turn.',
      'Watch how baby reacts to people they know versus someone new.',
      'Then call baby’s name from across the room.',
    ],
    whyItHelps: 'Telling familiar people from strangers is a healthy sign of attachment.',
    safetyNotes: ['Don’t push baby to go to someone they’re wary of. Shyness is normal and healthy.'],
    watchFor: [
      o('knows', 'Recognises familiar people (smiles, reaches, gets excited)', 'm6-knows-familiar'),
      o('shy', 'Is shy, clingy or wary with someone new', 'm9-strangers'),
      o('name', 'Looks when you call their name', 'm9-name'),
    ],
  },
  {
    id: 'tripod-sitting',
    title: 'Tripod sitting',
    ageMinDays: 140,
    ageMaxDays: 270,
    areas: ['motor'],
    durationMin: 5,
    materials: ['A cushion or rolled towel', 'A toy'],
    steps: [
      'Sit baby on the floor with a cushion behind them.',
      'Place a toy just in front, between their legs, so they lean forward onto their hands.',
      'Keep your hands close, ready to catch.',
    ],
    whyItHelps: 'Leaning on hands builds the balance and core strength for sitting on their own.',
    safetyNotes: ['Stay within arm’s reach. Babies tip over sideways a lot at this stage.'],
    watchFor: [
      o('leans', 'Leans on hands to hold themself up', 'm6-leans-hands'),
      o('sits', 'Sits for a moment without any support', 'm9-sits'),
    ],
  },
  {
    id: 'mirror-faces',
    title: 'Who’s in the mirror?',
    ageMinDays: 150,
    ageMaxDays: 365,
    areas: ['social', 'cognitive'],
    durationMin: 4,
    materials: ['A mirror (unbreakable, or hold baby in front of a wall mirror)'],
    steps: [
      'Sit with baby in front of the mirror.',
      'Point: “Who’s that? That’s [name]! And that’s me!”.',
      'Make happy, surprised and sad faces and name each one.',
    ],
    whyItHelps: 'Mirrors build self-awareness, and naming feelings is the start of emotional understanding.',
    safetyNotes: [],
    watchFor: [
      o('mirror', 'Likes looking at themself', 'm6-mirror'),
      o('faces', 'Makes different facial expressions', 'm9-expressions'),
    ],
  },

  // ───────────────────────── 6–9 months ─────────────────────────
  {
    id: 'peek-a-boo',
    title: 'Peek-a-boo',
    ageMinDays: 150,
    ageMaxDays: 420,
    areas: ['social', 'cognitive'],
    durationMin: 4,
    materials: ['A muslin cloth or your hands'],
    steps: [
      'Hide your face behind your hands or a cloth.',
      'Say “Where did I go?” and wait a second or two.',
      '“Peek-a-boo!” Reveal your face with a big smile. Repeat and vary the timing.',
    ],
    whyItHelps: 'Teaches that things still exist when hidden (object permanence), and the build-up is great fun.',
    safetyNotes: [],
    watchFor: [
      o('laughs', 'Smiles or laughs at peek-a-boo', 'm9-peekaboo'),
      o('laugh-out', 'Laughs out loud', 'm6-laughs'),
    ],
  },
  {
    id: 'uh-oh-drop',
    title: 'Uh-oh, where did it go?',
    ageMinDays: 200,
    ageMaxDays: 365,
    areas: ['cognitive'],
    durationMin: 4,
    materials: ['A few toys', 'Baby in a high chair or sitting on the floor'],
    steps: [
      'Let baby hold a toy, then drop it (or let them drop it) off the tray or behind a cushion.',
      'Say “Uh-oh! Where did it go?”.',
      'Wait and watch where baby looks before you bring it back.',
    ],
    whyItHelps: 'Looking for a dropped toy shows baby knows it still exists. A big thinking milestone.',
    safetyNotes: [CHOKING_SAFETY],
    watchFor: [
      o('looks', 'Looks for the toy after it drops out of sight', 'm9-looks-dropped'),
      o('passes', 'Moves the toy from one hand to the other', 'm9-hand-to-hand'),
    ],
  },
  {
    id: 'kitchen-band',
    title: 'Kitchen band',
    ageMinDays: 200,
    ageMaxDays: 420,
    areas: ['cognitive', 'motor'],
    durationMin: 5,
    materials: ['Wooden spoons', 'A plastic bowl or pot', 'Two plastic cups'],
    steps: [
      'Sit on the floor with baby and the “instruments”.',
      'Bang two spoons together, then a spoon on the pot. Show a slow beat and a fast beat.',
      'Hand baby the items and copy whatever they do.',
    ],
    whyItHelps: 'Banging things together teaches cause and effect and builds two-handed coordination.',
    safetyNotes: [],
    watchFor: [
      o('bangs', 'Bangs two things together', 'm9-bangs'),
      o('passes', 'Moves an object from one hand to the other', 'm9-hand-to-hand'),
    ],
  },
  {
    id: 'babble-back',
    title: 'Babble back',
    ageMinDays: 170,
    ageMaxDays: 420,
    areas: ['language'],
    durationMin: 5,
    materials: [],
    steps: [
      'When baby babbles (“ba-ba”, “da-da”), repeat it back with excitement.',
      'Add a new sound: “ba-ba… ma-ma!”, then pause.',
      'Say “Mama” and “Dada” while pointing to each parent (or a photo).',
    ],
    whyItHelps: 'Babbling is speech practice. Your replies teach baby that sounds carry meaning.',
    safetyNotes: [],
    watchFor: [
      o('babbles', 'Babbles repeated sounds like “mamama” or “bababa”', 'm9-babbles'),
      o('turns', 'Takes turns babbling with you', 'm6-turn-taking'),
      o('mama', 'Uses “mama”, “dada” or a special name for a parent', 'm12-mama-dada'),
    ],
  },
  {
    id: 'up-up-away',
    title: 'Up, up and away',
    ageMinDays: 200,
    ageMaxDays: 420,
    areas: ['language', 'motor'],
    durationMin: 3,
    materials: [],
    steps: [
      'Crouch in front of baby, hold your arms out and ask “Up?”.',
      'Wait a few seconds for a signal before you lift them.',
      'Lift them high with a “Wheee!” and bring them down gently.',
    ],
    whyItHelps: 'Waiting for baby to ask teaches them that gestures are a way to communicate.',
    safetyNotes: ['Never throw baby in the air or shake them. Lift smoothly.'],
    watchFor: [o('arms-up', 'Lifts arms up to be picked up', 'm9-arms-up')],
  },
  {
    id: 'sitting-play-circle',
    title: 'Sitting play circle',
    ageMinDays: 200,
    ageMaxDays: 330,
    areas: ['motor', 'cognitive'],
    durationMin: 6,
    materials: ['3–4 toys'],
    steps: [
      'Sit baby on the floor with cushions around (not behind) them.',
      'Place toys in a circle around them: in front, to the sides, slightly behind.',
      'Encourage baby to twist and reach while staying seated.',
    ],
    whyItHelps: 'Twisting and reaching while sitting builds balance, and getting in and out of sitting builds strength.',
    safetyNotes: ['Play on a soft floor with nothing hard nearby.'],
    watchFor: [
      o('sits', 'Sits without support', 'm9-sits'),
      o('gets-up', 'Gets into a sitting position by themself', 'm9-gets-sitting'),
      o('passes', 'Moves a toy from one hand to the other', 'm9-hand-to-hand'),
    ],
  },
  {
    id: 'puffs-on-tray',
    title: 'Puffs on the tray',
    ageMinDays: 210,
    ageMaxDays: 450,
    areas: ['motor'],
    durationMin: 5,
    materials: ['A few melt-in-the-mouth puffs or soft food pieces', 'High chair'],
    steps: [
      'With baby sitting upright in the high chair, scatter 4–5 puffs on the tray.',
      'Let them work out how to pick them up. Don’t help too fast.',
      'Show your own “pinch” with your thumb and pointer finger.',
    ],
    whyItHelps: 'Picking up small things builds fine-motor control, from raking to the precise pincer grip.',
    safetyNotes: [
      'Only food that dissolves or squashes easily. No nuts, whole grapes or hard pieces.',
      'Baby must be sitting upright, and you must stay right there.',
    ],
    watchFor: [
      o('rakes', 'Rakes food towards themself with their fingers', 'm9-rakes'),
      o('pincer', 'Picks up a piece between thumb and pointer finger', 'm12-pincer'),
      o('feeds', 'Feeds themself a piece', 'm15-finger-feeds'),
    ],
  },
  {
    id: 'see-you-soon',
    title: 'See you soon',
    ageMinDays: 200,
    ageMaxDays: 420,
    areas: ['social', 'language'],
    durationMin: 3,
    materials: [],
    steps: [
      'While someone else is with baby, wave and say “Bye-bye, see you soon!”.',
      'Step out of sight for 10–20 seconds.',
      'Come back cheerfully: “I’m back!”. Always say goodbye. Never sneak out.',
    ],
    whyItHelps: 'Short, predictable goodbyes teach baby that you always come back. This makes separation easier later.',
    safetyNotes: [],
    watchFor: [
      o('reacts', 'Reacts when you leave (looks, reaches, or cries)', 'm9-reacts-leave'),
      o('waves', 'Waves bye-bye', 'm12-waves'),
    ],
  },
  {
    id: 'funny-faces',
    title: 'Funny faces',
    ageMinDays: 180,
    ageMaxDays: 400,
    areas: ['social'],
    durationMin: 3,
    materials: [],
    steps: [
      'Make a big surprised face: “Oh!”. Then a big happy face.',
      'Try a pretend-sad face: “Oh no…” (keep it brief and playful).',
      'Watch whether baby copies you or reacts differently to each.',
    ],
    whyItHelps: 'Reading and making faces is the foundation of emotional intelligence.',
    safetyNotes: [],
    watchFor: [
      o('expressions', 'Shows different facial expressions', 'm9-expressions'),
      o('laughs', 'Laughs', 'm6-laughs'),
    ],
  },
  {
    id: 'crawl-chase',
    title: 'Crawl chase',
    ageMinDays: 210,
    ageMaxDays: 420,
    areas: ['motor', 'social'],
    durationMin: 5,
    materials: ['A rolling ball or favourite toy'],
    steps: [
      'Get down on all fours near baby.',
      'Roll the ball slowly away and say “Let’s get it!”.',
      'Crawl after it together. Let baby “win”.',
    ],
    whyItHelps: 'Moving towards a goal builds strength, coordination and motivation. Babies move in many ways, and all of them count.',
    safetyNotes: ['Baby-proof the area: cover sockets, block stairs, clear small objects.'],
    watchFor: [
      o('moves', 'Moves towards the toy (crawling, scooting, rolling or shuffling)'),
      o('sits', 'Sits back up without support', 'm9-sits'),
    ],
  },

  // ───────────────────────── 9–12 months ─────────────────────────
  {
    id: 'toy-under-blanket',
    title: 'Toy under the blanket',
    ageMinDays: 240,
    ageMaxDays: 456,
    areas: ['cognitive'],
    durationMin: 4,
    materials: ['A small blanket or cloth', 'A favourite toy'],
    steps: [
      'Let baby watch as you hide the toy under the cloth.',
      'Ask “Where did it go?”.',
      'If they don’t search, leave a bit of the toy sticking out. Make it harder as they get it.',
    ],
    whyItHelps: 'Searching for a hidden toy shows memory and object permanence at work.',
    safetyNotes: ['Put the blanket away after play. Never leave it in baby’s sleep space.'],
    watchFor: [
      o('finds', 'Looks for the toy you hid', 'm12-finds-hidden'),
      o('looks', 'Looks for things that drop out of sight', 'm9-looks-dropped'),
    ],
  },
  {
    id: 'in-and-out',
    title: 'In the box, out the box',
    ageMinDays: 270,
    ageMaxDays: 500,
    areas: ['cognitive', 'motor'],
    durationMin: 5,
    materials: ['A cup, bowl or shoebox', '4–5 blocks or large toys'],
    steps: [
      'Drop a block into the container: “In!”. Tip it out: “Out!”.',
      'Hand baby a block and hold the container close.',
      'Cheer every “in”, even accidental ones.',
    ],
    whyItHelps: 'Filling and emptying teaches cause and effect, space and size, and hand control.',
    safetyNotes: [CHOKING_SAFETY],
    watchFor: [
      o('puts-in', 'Puts something in the container', 'm12-container'),
      o('pincer', 'Picks up with thumb and pointer finger', 'm12-pincer'),
    ],
  },
  {
    id: 'pat-a-cake',
    title: 'Pat-a-cake',
    ageMinDays: 240,
    ageMaxDays: 480,
    areas: ['social', 'language'],
    durationMin: 4,
    materials: [],
    steps: [
      'Sit face to face. Sing “Pat-a-cake, pat-a-cake, baker’s man…”.',
      'Clap along, then gently clap baby’s hands for them.',
      'Sing it again and pause, waiting for baby to join in.',
    ],
    whyItHelps: 'Rhymes with actions build memory, rhythm and early language.',
    safetyNotes: [],
    watchFor: [
      o('plays', 'Joins in with the game', 'm12-pat-a-cake'),
      o('claps', 'Claps', 'm15-claps'),
    ],
  },
  {
    id: 'couch-cruising',
    title: 'Couch cruising',
    ageMinDays: 270,
    ageMaxDays: 480,
    areas: ['motor'],
    durationMin: 5,
    materials: ['A sturdy sofa', 'A few toys'],
    steps: [
      'Place a toy on the sofa seat so baby wants to pull up to reach it.',
      'Once standing, move the toy a little further along the sofa.',
      'Encourage baby to step sideways while holding on.',
    ],
    whyItHelps: 'Pulling up and cruising build the leg strength and balance for walking.',
    safetyNotes: ['Make sure the furniture is stable and can’t tip. Cushion sharp corners.'],
    watchFor: [
      o('pulls', 'Pulls up to stand', 'm12-pulls-stand'),
      o('cruises', 'Walks sideways holding the furniture', 'm12-cruises'),
    ],
  },
  {
    id: 'little-sips',
    title: 'Little sips',
    ageMinDays: 240,
    ageMaxDays: 548,
    areas: ['motor'],
    durationMin: 3,
    materials: ['A small open cup', 'A little water'],
    steps: [
      'Pour just a sip or two of water into the cup.',
      'Hold the cup to baby’s lips and tip it gently. Let them control the pace.',
      'As they get better, let them hold it with you, then on their own.',
    ],
    whyItHelps: 'Open-cup drinking builds lip and hand control, and it’s a step towards independence.',
    safetyNotes: ['Only a small amount of water. Baby sitting upright.'],
    watchFor: [
      o('held', 'Drinks from an open cup while you hold it', 'm12-open-cup-held'),
      o('own', 'Drinks from an open cup on their own (spills are fine)', 'm18-open-cup'),
    ],
  },
  {
    id: 'stop-and-go',
    title: 'Stop & go',
    ageMinDays: 300,
    ageMaxDays: 548,
    areas: ['language', 'cognitive'],
    durationMin: 4,
    materials: ['A ball'],
    steps: [
      'Roll the ball back and forth with baby.',
      'Now and then, hold up a hand and say “Stop!” (or “No, wait!”) in a firm but friendly voice.',
      'Then say “Go!” and keep playing.',
    ],
    whyItHelps: 'Understanding “stop” and “no” is an early sign of language understanding, and it keeps baby safe.',
    safetyNotes: [],
    watchFor: [
      o('pauses', 'Pauses or stops when you say “stop” or “no”', 'm12-understands-no'),
      o('one-step', 'Follows a simple instruction without a gesture', 'm18-one-step'),
    ],
  },
  {
    id: 'whos-that',
    title: 'Who’s that?',
    ageMinDays: 270,
    ageMaxDays: 480,
    areas: ['language', 'social'],
    durationMin: 4,
    materials: ['Family photos (on paper or your phone)'],
    steps: [
      'Look at photos together. Point and name each person: “That’s Mama!”.',
      'Ask “Where’s Dada?” and wait.',
      'Name one or two everyday things too: “Ball! Cat!”.',
    ],
    whyItHelps: 'Naming the people and things baby loves most is how first words begin.',
    safetyNotes: [],
    watchFor: [
      o('mama', 'Says “mama”, “dada” or a special name for a parent', 'm12-mama-dada'),
      o('word', 'Tries to say another word', 'm15-one-two-words'),
    ],
  },

  // ───────────────────────── 12–15 months ─────────────────────────
  {
    id: 'walk-to-me',
    title: 'Walk to me',
    ageMinDays: 330,
    ageMaxDays: 548,
    areas: ['motor', 'social'],
    durationMin: 5,
    materials: [],
    steps: [
      'Kneel a short distance away with your arms open.',
      'Have baby stand holding the sofa (or another adult), then call them to you.',
      'Catch them with a big hug. Move a little further back each time.',
    ],
    whyItHelps: 'Short, safe distances build walking confidence. Your open arms are the motivation.',
    safetyNotes: ['Soft floor, no sharp edges nearby. Barefoot is best for balance.'],
    watchFor: [
      o('steps', 'Takes a few steps on their own', 'm15-few-steps'),
      o('walks', 'Walks without holding on to anything', 'm18-walks'),
    ],
  },
  {
    id: 'two-block-tower',
    title: 'Block tower',
    ageMinDays: 365,
    ageMaxDays: 640,
    areas: ['cognitive', 'motor'],
    durationMin: 5,
    materials: ['Large blocks, stacking cups or small boxes'],
    steps: [
      'Build a tower of two blocks and knock it down together: “Crash!”.',
      'Hand baby a block and hold the bottom one steady.',
      'Let them knock it down. That is half the fun.',
    ],
    whyItHelps: 'Stacking needs careful hand control, planning and patience.',
    safetyNotes: [CHOKING_SAFETY],
    watchFor: [
      o('stacks', 'Stacks at least two objects', 'm15-stacks-two'),
      o('holds-uses', 'Holds something in one hand while using the other', 'm24-holds-uses'),
    ],
  },
  {
    id: 'show-me',
    title: 'Show me!',
    ageMinDays: 365,
    ageMaxDays: 640,
    areas: ['social', 'language'],
    durationMin: 5,
    materials: ['A basket of toys and everyday objects'],
    steps: [
      'Sit together with the basket.',
      'Pick something up, look at it with interest and say “Ooh, look!”.',
      'Then let baby explore. When they show you something, respond with excitement.',
    ],
    whyItHelps: 'Sharing attention (“look at this!”) is a key social skill and the base of conversation.',
    safetyNotes: [CHOKING_SAFETY],
    watchFor: [
      o('shows', 'Shows you an object they like', 'm15-shows-object'),
      o('points', 'Points to show you something interesting', 'm18-points-show'),
    ],
  },
  {
    id: 'teddy-bedtime',
    title: 'Teddy’s bedtime',
    ageMinDays: 365,
    ageMaxDays: 730,
    areas: ['social', 'cognitive'],
    durationMin: 5,
    materials: ['A soft toy', 'A small cloth as a “blanket”'],
    steps: [
      'Say “Teddy is sleepy!” and give teddy a hug and a kiss.',
      'Tuck teddy in with the cloth and sing a short lullaby.',
      'Hand teddy to baby: “Can you give teddy a cuddle?”.',
    ],
    whyItHelps: 'Caring for a toy is early pretend play, and it practises empathy.',
    safetyNotes: [],
    watchFor: [
      o('hugs', 'Hugs the toy', 'm15-hugs-toy'),
      o('affection', 'Shows you affection (hugs, cuddles, kisses)', 'm15-affection'),
    ],
  },
  {
    id: 'hello-phone',
    title: 'Hello, phone!',
    ageMinDays: 365,
    ageMaxDays: 640,
    areas: ['cognitive', 'language'],
    durationMin: 4,
    materials: ['A toy phone, or an old phone with no battery', 'A cup', 'A book'],
    steps: [
      'Hold the phone to your ear: “Hello? Oh, hi Grandma!”.',
      'Hand it to baby: “It’s for you!”.',
      'Do the same with the cup (pretend sip) and the book (open it).',
    ],
    whyItHelps: 'Using objects the “right way” shows baby understands what things are for.',
    safetyNotes: ['Remove batteries from old phones and remotes. Button batteries are very dangerous if swallowed.'],
    watchFor: [
      o('uses', 'Uses an object the right way (phone to ear, cup to mouth)', 'm15-uses-right'),
      o('word', 'Tries to say a word like “hello” or “hi”', 'm15-one-two-words'),
    ],
  },
  {
    id: 'wheres-the-ball',
    title: 'Where’s the ball?',
    ageMinDays: 365,
    ageMaxDays: 640,
    areas: ['language', 'cognitive'],
    durationMin: 4,
    materials: ['3 familiar objects: a ball, a cup, a shoe'],
    steps: [
      'Place the objects on the floor in front of baby.',
      'Ask “Where’s the ball?” without pointing. Wait.',
      'If they look at it, cheer. If not, point and name it, then try another.',
    ],
    whyItHelps: 'Babies understand far more words than they can say. This shows you what they know.',
    safetyNotes: [],
    watchFor: [o('looks', 'Looks at the object when you name it', 'm15-looks-named')],
  },
  {
    id: 'give-it-to-me',
    title: 'Give it to me',
    ageMinDays: 365,
    ageMaxDays: 640,
    areas: ['language', 'social'],
    durationMin: 4,
    materials: ['A few toys'],
    steps: [
      'Hold out your hand and say “Give me the ball, please” while pointing at it.',
      'Say “Thank you!” with a big smile, then give it back.',
      'Later, try the same request without pointing.',
    ],
    whyItHelps: 'Following directions shows growing understanding. Taking turns giving is also early sharing.',
    safetyNotes: [],
    watchFor: [
      o('gesture', 'Follows a direction when you use words and a gesture', 'm15-gesture-directions'),
      o('no-gesture', 'Follows a one-step direction without a gesture', 'm18-one-step'),
    ],
  },
  {
    id: 'what-do-you-want',
    title: 'What do you want?',
    ageMinDays: 380,
    ageMaxDays: 640,
    areas: ['language', 'cognitive'],
    durationMin: 3,
    materials: ['Two snacks or two toys'],
    steps: [
      'Hold up two choices, one in each hand, out of reach.',
      'Ask “Banana or cracker?” and wait.',
      'Give whatever baby points to or reaches for, naming it: “Banana!”.',
    ],
    whyItHelps: 'Offering choices gives baby a reason to communicate, and pointing is a huge step towards words.',
    safetyNotes: [],
    watchFor: [o('points', 'Points to ask for something', 'm15-points-ask')],
  },
  {
    id: 'little-playdate',
    title: 'Little playdate',
    ageMinDays: 380,
    ageMaxDays: 730,
    areas: ['social'],
    durationMin: 10,
    materials: ['Another child (a cousin, neighbour or friend)'],
    steps: [
      'Sit near the children with a few similar toys (two balls, two cups).',
      'Let them play side by side. Don’t force sharing at this age.',
      'Stay nearby as a safe base.',
    ],
    whyItHelps: 'Toddlers learn a lot by watching and copying other children.',
    safetyNotes: ['Stay close. Toddlers may grab, push or bite without meaning harm.'],
    watchFor: [
      o('copies', 'Copies the other child while playing', 'm15-copies-children'),
      o('checks', 'Moves away but looks back to check you’re there', 'm18-checks-back'),
    ],
  },
  {
    id: 'happy-and-you-know-it',
    title: 'If you’re happy and you know it',
    ageMinDays: 330,
    ageMaxDays: 730,
    areas: ['social', 'language'],
    durationMin: 4,
    materials: [],
    steps: [
      'Sing “If you’re happy and you know it, clap your hands!”.',
      'Add verses: stamp your feet, blow a kiss, nod your head.',
      'Do the actions big and slow so baby can copy.',
    ],
    whyItHelps: 'Action songs combine words, rhythm and gestures. Gestures often come before words.',
    safetyNotes: [],
    watchFor: [
      o('claps', 'Claps when excited', 'm15-claps'),
      o('gestures', 'Uses gestures like blowing a kiss or nodding', 'm24-more-gestures'),
    ],
  },

  // ───────────────────────── 15–18 months ─────────────────────────
  {
    id: 'first-scribbles',
    title: 'First scribbles',
    ageMinDays: 420,
    ageMaxDays: 730,
    areas: ['motor', 'cognitive'],
    durationMin: 5,
    materials: ['Chunky non-toxic crayons', 'A large sheet of paper taped to the table or floor'],
    steps: [
      'Tape the paper down so it doesn’t slide.',
      'Make a few big lines and circles yourself: “Round and round!”.',
      'Hand baby a crayon and admire every mark.',
    ],
    whyItHelps: 'Scribbling builds hand and wrist control, the long road to writing.',
    safetyNotes: ['Stay close. Crayons often go in the mouth at this age.'],
    watchFor: [
      o('scribbles', 'Scribbles on the paper', 'm18-scribbles'),
      o('holds-uses', 'Holds the paper with one hand while drawing with the other', 'm24-holds-uses'),
    ],
  },
  {
    id: 'little-helper',
    title: 'Little helper',
    ageMinDays: 420,
    ageMaxDays: 730,
    areas: ['cognitive', 'social'],
    durationMin: 6,
    materials: ['A cloth, a small brush or a toy broom'],
    steps: [
      'While you tidy or wipe the table, give baby their own cloth or brush.',
      'Narrate: “Wipe, wipe, wipe! We’re cleaning!”.',
      'Thank them for helping, however messy.',
    ],
    whyItHelps: 'Toddlers learn by imitation. Being included in real tasks builds confidence.',
    safetyNotes: ['Keep cleaning products well away.'],
    watchFor: [o('copies', 'Copies you doing a chore', 'm18-copies-chores')],
  },
  {
    id: 'dress-up-help',
    title: 'Dress-up & wash-up helper',
    ageMinDays: 420,
    ageMaxDays: 730,
    areas: ['social', 'motor'],
    durationMin: 5,
    materials: ['Baby’s clothes', 'A basin or sink for hand washing'],
    steps: [
      'When dressing, hold the sleeve open and say “Arm in!”, then wait.',
      'Do the same with socks: “Foot up!”.',
      'Before a meal, sing a hand-washing song and hold out your hands to wash theirs.',
    ],
    whyItHelps: 'Taking part in daily routines builds independence, cooperation and body awareness.',
    safetyNotes: ['Check water temperature first.'],
    watchFor: [
      o('dress', 'Helps by pushing an arm through or lifting a foot', 'm18-helps-dress'),
      o('wash', 'Puts hands out for you to wash them', 'm18-hands-wash'),
    ],
  },
  {
    id: 'book-cuddle',
    title: 'Book cuddle',
    ageMinDays: 300,
    ageMaxDays: 730,
    areas: ['language', 'social'],
    durationMin: 6,
    materials: ['A board book with clear pictures'],
    steps: [
      'Sit baby on your lap with the book.',
      'Don’t read every word. Point at pictures and name them.',
      'Ask “Where’s the dog?” and wait for them to look or point.',
    ],
    whyItHelps: 'Sharing books is one of the strongest boosters of early language.',
    safetyNotes: [],
    watchFor: [
      o('pages', 'Looks at a few pages with you', 'm18-book-pages'),
      o('named', 'Looks at a picture when you name it', 'm15-looks-named'),
      o('points', 'Points to things in the book when you ask', 'm24-points-book'),
    ],
  },
  {
    id: 'vroom-vroom',
    title: 'Vroom vroom',
    ageMinDays: 400,
    ageMaxDays: 730,
    areas: ['cognitive', 'motor'],
    durationMin: 5,
    materials: ['A toy car or truck', 'Blocks or a box for a “garage”'],
    steps: [
      'Push the car along the floor: “Vroom!”.',
      'Drive it into the box-garage, then out again.',
      'Hand the car to baby and follow their lead.',
    ],
    whyItHelps: 'Simple play with toys is the start of imaginative play and problem solving.',
    safetyNotes: [CHOKING_SAFETY],
    watchFor: [
      o('pushes', 'Plays with the toy in a simple way, like pushing the car', 'm18-simple-play'),
      o('multi', 'Plays with more than one toy at a time', 'm24-multi-toys'),
    ],
  },
  {
    id: 'spoon-practice',
    title: 'Spoon practice',
    ageMinDays: 365,
    ageMaxDays: 730,
    areas: ['motor'],
    durationMin: 10,
    materials: ['A thick, easy-grip spoon', 'Sticky food like yoghurt or mashed potato'],
    steps: [
      'Give baby their own spoon while you feed them with another.',
      'Load their spoon and let them bring it to their mouth.',
      'Expect mess. It’s part of learning.',
    ],
    whyItHelps: 'Self-feeding builds coordination and independence.',
    safetyNotes: ['Baby sitting upright. Stay with them throughout.'],
    watchFor: [
      o('fingers', 'Feeds themself with their fingers', 'm18-self-feeds'),
      o('tries', 'Tries to use the spoon', 'm18-tries-spoon'),
      o('eats', 'Eats with a spoon', 'm24-eats-spoon'),
    ],
  },
  {
    id: 'cushion-mountain',
    title: 'Cushion mountain',
    ageMinDays: 420,
    ageMaxDays: 730,
    areas: ['motor'],
    durationMin: 6,
    materials: ['Sofa cushions', 'A low sofa or armchair'],
    steps: [
      'Pile cushions on the floor to make a small “mountain”.',
      'Help baby climb over it, then on and off the sofa.',
      'Show how to get down safely: tummy down, feet first.',
    ],
    whyItHelps: 'Climbing builds strength, balance and body planning, and it teaches safe ways down.',
    safetyNotes: ['Soft floor, away from sharp corners and windows. Stay within reach.'],
    watchFor: [
      o('climbs', 'Climbs on and off the sofa without help', 'm18-climbs-couch'),
      o('walks', 'Walks without holding on', 'm18-walks'),
    ],
  },
  {
    id: 'word-of-the-day',
    title: 'Word of the day',
    ageMinDays: 420,
    ageMaxDays: 730,
    areas: ['language'],
    durationMin: 5,
    materials: ['One everyday object (a cup, a ball, a banana)'],
    steps: [
      'Pick one word for today and use it many times: “Cup! Your cup. Big cup!”.',
      'Pause and give baby a chance to say it.',
      'Expand what they say: if they say “cup”, you say “More cup!”.',
    ],
    whyItHelps: 'Hearing a word many times in a short period helps it stick. Expanding what baby says models the next step.',
    safetyNotes: [],
    watchFor: [
      o('three', 'Uses three or more words besides “mama” or “dada”', 'm18-three-words'),
      o('two-together', 'Puts two words together, like “more cup”', 'm24-two-words'),
    ],
  },
  {
    id: 'explore-and-check-in',
    title: 'Explore & check-in',
    ageMinDays: 420,
    ageMaxDays: 730,
    areas: ['social', 'cognitive'],
    durationMin: 10,
    materials: ['A park, a courtyard, or a new room'],
    steps: [
      'Take baby somewhere new and safe. Sit down and let them explore.',
      'Stay put and be available. Smile when they look back.',
      'Name what they point at: “Yes, a bird!”.',
    ],
    whyItHelps: 'Exploring with you as a safe base builds confidence. Checking your face tells them what’s safe.',
    safetyNotes: ['Choose an enclosed or traffic-free area. Keep baby in sight at all times.'],
    watchFor: [
      o('checks', 'Moves away but looks back to check you’re close by', 'm18-checks-back'),
      o('points', 'Points to show you something interesting', 'm18-points-show'),
      o('reference', 'Looks at your face to see how to react to something new', 'm24-social-ref'),
    ],
  },

  // ───────────────────────── 18–24 months ─────────────────────────
  {
    id: 'wheres-your-nose',
    title: 'Where’s your nose?',
    ageMinDays: 480,
    ageMaxDays: 730,
    areas: ['language', 'cognitive'],
    durationMin: 4,
    materials: [],
    steps: [
      'Touch your nose: “Nose!”. Then gently touch baby’s nose.',
      'Ask “Where’s your nose?” and wait.',
      'Add tummy, ears, feet and hands one at a time.',
    ],
    whyItHelps: 'Body parts are some of the first words toddlers learn, and following a question builds understanding.',
    safetyNotes: [],
    watchFor: [
      o('body', 'Points to at least two body parts when you ask', 'm24-body-parts'),
      o('one-step', 'Follows a one-step direction without a gesture', 'm18-one-step'),
    ],
  },
  {
    id: 'kick-the-ball',
    title: 'Kick the ball',
    ageMinDays: 480,
    ageMaxDays: 730,
    areas: ['motor', 'social'],
    durationMin: 6,
    materials: ['A large soft ball'],
    steps: [
      'Show how to kick: stand on one foot and swing the other gently.',
      'Place the ball in front of baby’s foot and cheer: “Kick!”.',
      'Kick it back and forth. Chase it together.',
    ],
    whyItHelps: 'Kicking needs balance on one leg, a big step in coordination.',
    safetyNotes: ['Play away from roads, stairs and hard furniture.'],
    watchFor: [
      o('kicks', 'Kicks the ball', 'm24-kicks'),
      o('runs', 'Runs after it', 'm24-runs'),
    ],
  },
  {
    id: 'chase-me',
    title: 'Chase me!',
    ageMinDays: 500,
    ageMaxDays: 730,
    areas: ['motor', 'social'],
    durationMin: 5,
    materials: [],
    steps: [
      'Say “I’m going to get you!” and chase slowly.',
      'Then swap: “Can you catch me?” and run slowly away.',
      'Let them catch you and fall over dramatically.',
    ],
    whyItHelps: 'Running games build speed, balance and stamina, and lots of laughter.',
    safetyNotes: ['Clear the space. Toddlers fall often when running.'],
    watchFor: [o('runs', 'Runs', 'm24-runs')],
  },
  {
    id: 'stair-climbers',
    title: 'Stair climbers',
    ageMinDays: 480,
    ageMaxDays: 730,
    areas: ['motor'],
    durationMin: 4,
    materials: ['A few stairs'],
    steps: [
      'Hold baby’s hand and walk up two or three stairs together.',
      'Count each step: “One, two, three!”.',
      'Come down together, or show them how to go down backwards on their tummy.',
    ],
    whyItHelps: 'Stairs build leg strength, balance and body planning.',
    safetyNotes: ['Always stay one step below and hold hands. Use a gate when not playing.'],
    watchFor: [o('stairs', 'Walks (not crawls) up a few stairs, with or without help', 'm24-stairs')],
  },
  {
    id: 'teddy-boo-boo',
    title: 'Teddy has a boo-boo',
    ageMinDays: 500,
    ageMaxDays: 730,
    areas: ['social'],
    durationMin: 4,
    materials: ['A soft toy', 'A plaster or cloth'],
    steps: [
      'Say “Oh no, teddy bumped his knee! He’s sad.” Show a sad face.',
      'Ask “Can you help teddy feel better?”.',
      'Put on a plaster together, give a hug, and show teddy happy again.',
    ],
    whyItHelps: 'Pretending to care for someone hurt is early empathy.',
    safetyNotes: [],
    watchFor: [
      o('notices', 'Notices teddy is hurt or sad', 'm24-notices-upset'),
      o('affection', 'Hugs or kisses teddy (or you)', 'm15-affection'),
    ],
  },
  {
    id: 'push-twist-open',
    title: 'Push, twist, open',
    ageMinDays: 450,
    ageMaxDays: 730,
    areas: ['cognitive', 'motor'],
    durationMin: 5,
    materials: ['A toy with buttons or switches, or lids and containers with easy screw tops'],
    steps: [
      'Show how one button works: “Push! Beep!”.',
      'Give baby a turn. Wait before helping.',
      'Try a loose lid: “Twist, twist… open!”.',
    ],
    whyItHelps: 'Buttons and lids teach cause and effect and build finger strength.',
    safetyNotes: ['Check battery covers are screwed shut.'],
    watchFor: [
      o('switches', 'Tries buttons, switches or knobs', 'm24-switches'),
      o('holds-uses', 'Holds a container in one hand while working it with the other', 'm24-holds-uses'),
    ],
  },
  {
    id: 'more-please',
    title: 'More, please',
    ageMinDays: 500,
    ageMaxDays: 730,
    areas: ['language'],
    durationMin: 5,
    materials: ['A snack in small portions'],
    steps: [
      'Give a small portion, then wait.',
      'When baby wants more, model the words: “More banana?”.',
      'Model gestures too: nod “yes”, shake “no”, blow a kiss for “thank you”.',
    ],
    whyItHelps: 'Everyday routines are the best language lessons. Small portions create many chances to ask.',
    safetyNotes: ['Cut food into safe sizes. Baby sitting down while eating.'],
    watchFor: [
      o('two-words', 'Says two words together, like “more milk”', 'm24-two-words'),
      o('gestures', 'Nods yes, blows a kiss or uses another new gesture', 'm24-more-gestures'),
    ],
  },
  {
    id: 'something-new',
    title: 'Something new',
    ageMinDays: 480,
    ageMaxDays: 730,
    areas: ['social', 'cognitive'],
    durationMin: 4,
    materials: ['A new, safe object baby hasn’t seen (a whisk, a funnel, a wind-up toy)'],
    steps: [
      'Bring out the new thing and set it down between you.',
      'Wait a moment before reacting. See if baby looks at you first.',
      'Then show you’re calm and interested: “Ooh, what’s this?”.',
    ],
    whyItHelps: 'Toddlers read your face to decide if something is safe. Your calm confidence shapes how they explore.',
    safetyNotes: [CHOKING_SAFETY],
    watchFor: [o('reference', 'Looks at your face to see how to react', 'm24-social-ref')],
  },
  {
    id: 'tea-party',
    title: 'Tea party',
    ageMinDays: 500,
    ageMaxDays: 730,
    areas: ['cognitive', 'social'],
    durationMin: 8,
    materials: ['Toy or plastic cups, plates and spoons', 'A couple of soft toys as guests'],
    steps: [
      'Set out cups and plates for you, baby and the toys.',
      'Pour pretend tea: “Would teddy like some tea?”.',
      'Follow baby’s lead: feed the toys, stir, “sip”.',
    ],
    whyItHelps: 'Pretend play combines imagination, language and social understanding.',
    safetyNotes: [],
    watchFor: [
      o('multi', 'Plays with more than one toy at the same time', 'm24-multi-toys'),
      o('uses', 'Uses the cup and spoon the right way in play', 'm15-uses-right'),
    ],
  },
]

export const gameById = new Map(games.map((g) => [g.id, g]))
